//! Generated by `scripts/generate-invisible-table.py`; do not edit by hand.
//!
//! `Default_Ignorable_Code_Point ∪ Cf` from the pinned Unicode Character Database
//! snapshot extracted under `crates/secret-scan-core/ucd/`
//! (`decision-normalize-invisible-characters-before-detection`).
//! 25 ranges, 4206 code points.

/// The Unicode Character Database version the table was derived from.
#[cfg(test)]
pub(crate) const UCD_VERSION: &str = "17.0.0";

/// Sorted, disjoint, non-adjacent inclusive code-point ranges. None is
/// ASCII; the generator rejects a snapshot that would make one so.
#[rustfmt::skip]
pub(crate) const INVISIBLE_RANGES: &[(u32, u32)] = &[
    (0x00AD, 0x00AD),
    (0x034F, 0x034F),
    (0x0600, 0x0605),
    (0x061C, 0x061C),
    (0x06DD, 0x06DD),
    (0x070F, 0x070F),
    (0x0890, 0x0891),
    (0x08E2, 0x08E2),
    (0x115F, 0x1160),
    (0x17B4, 0x17B5),
    (0x180B, 0x180F),
    (0x200B, 0x200F),
    (0x202A, 0x202E),
    (0x2060, 0x206F),
    (0x3164, 0x3164),
    (0xFE00, 0xFE0F),
    (0xFEFF, 0xFEFF),
    (0xFFA0, 0xFFA0),
    (0xFFF0, 0xFFFB),
    (0x110BD, 0x110BD),
    (0x110CD, 0x110CD),
    (0x13430, 0x1343F),
    (0x1BCA0, 0x1BCA3),
    (0x1D173, 0x1D17A),
    (0xE0000, 0xE0FFF),
];
