//! The checked-in invisible-code-point table matches a regeneration
//! (`decision-normalize-invisible-characters-before-detection`).
//!
//! `src/invisible_table.rs` is generated by
//! `scripts/generate-invisible-table.py` from the pinned UCD extracts under
//! `ucd/`. This test re-derives `Default_Ignorable_Code_Point ∪ Cf` from the
//! same extracts with its own parser and compares it with the ranges the
//! generated source declares, so a hand edit, a stale table, or a generator
//! defect is a test failure and a UCD bump is a reviewable diff.
//! `npm run rust:check` additionally asserts the file byte for byte.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

const DERIVED_CORE_PROPERTIES: &str = include_str!("../ucd/DerivedCoreProperties.txt");
const UNICODE_DATA: &str = include_str!("../ucd/UnicodeData.txt");
const GENERATED_TABLE: &str = include_str!("../src/invisible_table.rs");

fn code_point(text: &str) -> u32 {
    u32::from_str_radix(text.trim(), 16).unwrap()
}

/// Every code point the pinned extracts place in the removed set.
fn derived_set() -> Vec<u32> {
    let mut set = Vec::new();
    for line in DERIVED_CORE_PROPERTIES.lines() {
        let record = line.split('#').next().unwrap();
        let Some((span, property)) = record.split_once(';') else {
            continue;
        };
        assert_eq!(property.trim(), "Default_Ignorable_Code_Point");
        let (first, last) = span.split_once("..").unwrap_or((span, span));
        set.extend(code_point(first)..=code_point(last));
    }
    for line in UNICODE_DATA.lines().filter(|line| !line.starts_with('#')) {
        let fields: Vec<&str> = line.split(';').collect();
        assert_eq!(fields[2], "Cf");
        assert!(!fields[1].ends_with(", First>") && !fields[1].ends_with(", Last>"));
        set.push(code_point(fields[0]));
    }
    set.sort_unstable();
    set.dedup();
    set
}

/// Every code point the generated source declares, from its `(0x…, 0x…),`
/// lines.
fn declared_set() -> Vec<u32> {
    let mut set = Vec::new();
    for line in GENERATED_TABLE.lines() {
        let Some(pair) = line
            .trim()
            .strip_prefix('(')
            .and_then(|rest| rest.strip_suffix("),"))
        else {
            continue;
        };
        let (first, last) = pair.split_once(", ").unwrap();
        let first = code_point(first.strip_prefix("0x").unwrap());
        let last = code_point(last.strip_prefix("0x").unwrap());
        assert!(set.last().is_none_or(|&previous| previous + 1 < first));
        set.extend(first..=last);
    }
    set
}

#[test]
fn the_checked_in_table_matches_a_regeneration_from_the_pinned_ucd() {
    let derived = derived_set();
    assert!(derived.len() > 4_000);
    assert_eq!(declared_set(), derived);
}

#[test]
fn the_table_and_both_extracts_name_the_same_ucd_version() {
    let version = GENERATED_TABLE
        .lines()
        .find_map(|line| line.strip_prefix("pub(crate) const UCD_VERSION: &str = \""))
        .and_then(|rest| rest.strip_suffix("\";"))
        .unwrap();
    for extract in [DERIVED_CORE_PROPERTIES, UNICODE_DATA] {
        let header = extract.lines().next().unwrap();
        assert!(header.ends_with(&format!("Unicode Character Database {version}.")));
    }
}

#[test]
fn no_removed_code_point_is_ascii_or_a_line_terminator() {
    // The pipeline's `is_ascii()` fast path and the incremental sanitizer's
    // unit boundaries both depend on this.
    assert!(derived_set().iter().all(|&code_point| code_point >= 0x80));
}
