"""The side-effect-free `artifact_manifest()` query (issue #1250).

The manifest is generated by the Rust core from the registration rows the
module links; these tests pin the Python surface (types, no side effect, the
shared canonical-JSON contract) and reconcile it with the reviewed detector
inventory. There is no Python copy of the detector catalog.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from typing import Any

import pytest
import redact_secret
from .conftest import REPO_ROOT, load_corpus


def _canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _child(source: str) -> object:
    completed = subprocess.run(
        [sys.executable, "-c", source],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(completed.stdout)


def test_artifact_manifest_is_exported_and_takes_no_input() -> None:
    assert "artifact_manifest" in redact_secret.__all__
    assert isinstance(redact_secret.artifact_manifest(), dict)
    with pytest.raises(TypeError):
        redact_secret.artifact_manifest("x")  # type: ignore[call-arg]


def test_manifest_identifies_this_wheel() -> None:
    manifest = redact_secret.artifact_manifest()
    assert manifest["schema"] == "artifact-manifest/v1"
    assert manifest["product"] == "redact-secret"
    assert manifest["version"] == redact_secret.VERSION
    assert manifest["artifact"] == {"kind": "python-wheel", "pii": True, "variant": "full"}
    assert manifest["composition"] == {"id": None, "kind": "standard", "profile": "full"}
    assert manifest["notIncluded"] == []
    assert manifest["capabilities"]["detectorSelection"] is False
    assert manifest["defaults"]["schema"] == "build-defaults/v1"
    assert manifest["typeVocabulary"]["complete"] is False
    assert next(iter(manifest)) == "schema"


def test_manifest_digest_is_the_sha256_of_the_canonical_document_without_digest() -> None:
    manifest = redact_secret.artifact_manifest()
    digest = manifest.pop("digest")
    expected = "sha256:" + hashlib.sha256(_canonical(manifest).encode("utf-8")).hexdigest()
    assert digest == expected


def test_canonical_json_fixture_cases() -> None:
    fixture = load_corpus("artifact-manifest-v1.json")
    assert fixture["cases"]
    for case in fixture["cases"]:
        canonical = _canonical(case["input"])
        assert canonical == case["canonical"], case["name"]
        assert hashlib.sha256(canonical.encode("utf-8")).hexdigest() == case["sha256"], case["name"]
    assert sorted(redact_secret.artifact_manifest()) == fixture["manifest"]["members"]


def test_detectors_equal_the_reviewed_inventory() -> None:
    inventory = json.loads((REPO_ROOT / "docs" / "coverage" / "detector-inventory.json").read_text(encoding="utf-8"))
    reviewed: dict[str, set[str]] = {}
    for row in inventory["types"]:
        reviewed.setdefault(row["detector"], set()).add(row["type"])
    detectors = redact_secret.artifact_manifest()["detectors"]
    assert {entry["id"] for entry in detectors} == set(reviewed)
    assert len(detectors) == len(reviewed)
    for entry in detectors:
        assert set(entry["types"]) == reviewed[entry["id"]], entry["id"]
        assert entry["types"] == sorted(entry["types"])
        assert entry["aliases"] == []
        assert entry["pack"] in {"common", "provider"}


def test_manifest_is_deterministic_and_leaks_no_input_or_literal() -> None:
    first = json.dumps(redact_secret.artifact_manifest())
    assert first == json.dumps(redact_secret.artifact_manifest())
    assert first.isascii()
    for forbidden in ("://", "localhost", "/Users/", "\\\\"):
        assert forbidden not in first


def test_manifest_does_not_initialize_or_lock_the_pii_selection() -> None:
    child = """
import json, redact_secret
redact_secret.artifact_manifest()
before = redact_secret.status()
redact_secret.artifact_manifest()
redact_secret.initialize(pii=["pii"])
after = redact_secret.status()
print(json.dumps({
    "before": [before.initialized, before.activation],
    "after": [after.initialized, "selectors=pii:global" in (after.activation or "")],
}))
"""
    actual = _child(child)
    assert isinstance(actual, dict)
    # Reading the manifest neither initialized nor locked the selection, so a
    # later initialize with a PII selection still applied.
    assert actual["before"] == [False, None]
    assert actual["after"] == [True, True]
